version: "3.8"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/billeteraseca
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: billetera123
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: billeteraseca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: billetera123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
