name: CI Build

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Cache Gradle dependencies
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      # Step 4: Install Gradle dependencies
      - name: Install dependencies
        run: ./gradlew build --no-daemon

      # Step 5: Run tests
      - name: Run tests
        run: ./gradlew test --no-daemon

      # Step 6: Build the project
      - name: Build project (JAR file)
        run: ./gradlew build --no-daemon
